"""项目级默认值常量，供 pipeline / CLI / UI 层统一引用。"""

DEFAULT_CHUNK_SIZE = 500
DEFAULT_OVERLAP = 50
DEFAULT_EMBED_DIM = 256
DEFAULT_TOP_K = 3
DEFAULT_PREVIEW = 3
DEFAULT_TEMPERATURE = 0.2
DEFAULT_LLM_TIMEOUT = 120.0
DEFAULT_LLM_MAX_RETRIES = 1
DEFAULT_LLM_PROVIDER = "local"
DEFAULT_LLM_MODEL = "gpt-4o-mini"
DEFAULT_LLM_API_KEY_ENV = "OPENAI_API_KEY"
